### ISSUE TITLE
Launch Issue

### ISSUE THREAD

**Issue by shavy4452** [milinddhamu/coc-nextjs#19]
This is probably looking like next.js navbar error, can you suggest with the fix. I am trying to replace royalapi api with clashofclans.js library.
![image](https://github.com/milinddhamu/coc-nextjs/assets/61879715/6be7ecdf-8080-415c-bbeb-a3c8518900b9)

**Comment by shavy4452** [comment]
Dependency issue, got it solved.

**Comment by tc-maxx** [comment]
Can you describe how you solved it?

**Comment by milinddhamu** [comment]
> Can you describe how you solved it?

Try deleting node modules and then re-installing , dont update packages as of new package.

**Comment by shavy4452** [comment]
Exactly, It is the dependency error basically quick fix is to not upgrade the package dependency, in next release we will be changing the style manager.

If you face this issue, try this

- remove your node_modules folder
- rollback the package.json file or download the package.json file again
- npm install
Thats all to be done, dont do 'npm update`

**Comment by shavy4452** [comment]
@milinddhamu  we can close this as per now. @tc-maxx  reopen a issue if still face an error.
